name: cryosiam
channels:
  - nvidia
  - pytorch
  - conda-forge

dependencies:
  - python>=3.8
  - numpy
  - pandas
  - scipy
  - h5py
  - scikit-learn
  - pytorch
  - torchvision
  - pytorch-cuda
  - itk
  - pyyaml
  - plotly
  - python-elf
  - lightning
  - monai>=1.3.1
  - mrcfile
  - starfile
  - scikit-image
  - pip
  - pip:
      - edt
      - umap-learn